version: '3.9'

services:

  blog_web:

    build: ./
    command: sh -c "alembic upgrade head && uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8080"
    volumes:
      - .:/usr/src/app/
    ports:
      - 8080:8080
    env_file:
      - .env./
    depends_on:
      - blog-db

  blog-db:

    image: postgres:14.6-alpine
    volumes:
      - blog_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  blog_postgres_data: